### PR TITLE
Add product label name to the load view modal, fix infinite loading while fetching map product

### PR DESCRIPTION
**Pull request by danielkryska**
IMPORTANT!!! 
Bakground loader never ends due to issue linked with never triggered event renderend on map. Occurs in case of CORS.

- Force map loader to stop on
  - View change
  - Scene change
- Add product label name to the load view modal

### CODE REVIEW

**Comment by Marcelinna** [comment]
I don't know that 5 sec is enough? on production, for example, for " Charakterystyka powierzchni o wysokiej rozdzielczości " after 5 sec nothing has loaded yet. I have to wait longer, and all scene is loading approximately after 30 seconds.

**Comment by jswk** [comment]
> I don't know that 5 sec is enough? on production, for example, for " Charakterystyka powierzchni o wysokiej rozdzielczości " after 5 sec nothing has loaded yet. I have to wait longer, and all scene is loading approximately after 30 seconds.

I also think that 5 seconds isn't long enough, although I would rather not have any timeout on this. Having the loader reset on scene change (and therefore product change) is enough.
I think a user would try navigating to another scene anyway, if she encounters a problem with loading, thus resetting the loader.

Btw, one possibly extra case for loader reset: overlay change, as it triggers reload as well.

**Comment by Marcelinna** [comment]
extra case for loader reset too: turning off the product.

**Comment by danielkryska** [comment]
Timeout made to stop background after time of 5 sec have been removed

**Review by Marcelinna — APPROVED** [review]

**Review by jswk — APPROVED** [review]
Correct the format so that liner passes. Otherwise, the PR is fine now.

**Pull request merged**
