### PR TITLE
[#1129] Sentinel search translated labels

### PR DESCRIPTION
**Pull request by michal-szostak**
## What is in this PR?

* Add translations to sentinel serach form labels
* Fix bug when after logging in as a user the sentinel metadata was not reloaded after revisiting sentinel search

### CODE REVIEW

**Comment by Marcelinna** [comment]
After click  "Szukaj Danych" error 500 is dipslayed, for a logged in and not logged in user

**Comment by jswk** [comment]
> After click "Szukaj Danych" error 500 is dipslayed, for a logged in and not logged in user

Right! I missed cloudCover in the tests. cc283d5f should correct this.

**Comment by Marcelinna** [comment]
I can check a few products at a time, only one should be possible and the button search is always disabled
image

**Comment by Marcelinna** [comment]
image
when sorting is "Czas spozycia" date is "detekcja od" and "detekcja do"

**Comment by jswk** [comment]
> when sorting is "Czas spozycia" date is "detekcja od" and "detekcja do"

This is correct. "Czas spożycia" is a metadata field available in Sentinel-1 and Sentinel-2. You should have a "Czas detekcji" in the "Sortuj po" select.

**Comment by Marcelinna** [comment]
on master I have to click on all div with name and select product, on PR I have to click in exactly input/checkbox

**Comment by jswk** [comment]
For a2acfe97, such situation (I chose to search for Sentinel 2 L1C, hit 'Szukaj' and went back):
image
There are `[object Object]` query params values and unselected params appear in the list. Moreover, there is an error in the console which appears on navigating to the search panel.

**Comment by Marcelinna** [comment]
on master first product is selected as default, on PR user can click search without selecting product 
image

**Comment by Marcelinna** [comment]
Plase delete unnecessary console.log() frome code 
image
image

**Review by Marcelinna — APPROVED** [review]

**Review by jswk — APPROVED** [review]

**Pull request merged**
