### PR TITLE
Legends creator

### PR DESCRIPTION
**Pull request by abacz**

### CODE REVIEW

**Comment by abacz** [comment]
@michal-szostak could you check web tests? thx

**Comment by jswk** [comment]
Why don't you add these legends to the `products.json`?

**Comment by abacz** [comment]
> Why don't you add these legends to the `products.json`?

I didn't know to put there.

**Review by jswk — APPROVED** [review]
From the backend perspective this is fine once you add the missing legend entries for other products in `products.json`.

**Comment by michal-szostak** [comment]
@abacz - is this one good? Do you just need some help with rebasing / tests?

**Comment by abacz** [comment]
@michal-szostak i've done my work in this PR

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
