### PR TITLE
Fix login backlink, fix locations search, fix redirect to settings dashboard

### PR DESCRIPTION
**Pull request by danielkryska**
- Fix fast selection of location in location search
- Fix active location color in location search
- Fix active location selection with mapa marker icon in location search
- Fix set/unset larger font
- Add map scale in map left top corner

### CODE REVIEW

**Review by jswk — CHANGES_REQUESTED** [review]
The backlink handling on unauthorized seems to work (although it works on master instance too, so it's a tad confusing).

However, it's not possible to navigate the place-search results by arrows now. The current item isn't highlighted anymore. Moreover, the bug with selecting "Abramowice Kościelne" when inputting something else and hitting enter before the results are loaded remains, but I don't know if it was in the scope of the PR ("fix search location on map" is unclear to me).

**Comment by Marcelinna** [comment]
as @jswk  mentioned
- lack of highlighting the city when navigating with arrows
- problem with the correct search of the town after pressing enter
(https://github.com/cyfronet-fid/sat4envi/issues/957)

**Comment by Marcelinna** [comment]
lack of highlighting the city when navigating with arrows still exist

**Review by jswk — CHANGES_REQUESTED** [review]
Tested on 581ba967.

#### Authorization problem
1. Go to map, unauthorized (logout if needed).
2. You get redirected to login, and cannot access the map. (If you click "przejdź do mapy", then you are redirected back to login).

#### Search navigation
1. Focus the search bar. Wait for basic results.
2. Type quickly "war" and hit Enter. Nothing happens, this problem is fixed.
3. When you hit enter again upon results loading you get to Wargawa.
4. Hit down arrow. Results show up. Try to navigate the results with arrows, go down 1 position to Wara, click Enter. Nothing happens, I would expect to be able to select an alternative result though.
5. This behaviour is inconsistent though. When you type Wargowo and are presented with two results, then choosing either one using the same method (with arrows) works. Yet, when you type "Tychów " and also two results appear, then choosing doesn't work again.

There's some inconsistency in this behaviour. It doesn't seem like blocker to me though. Nevertheless, not being able to browse as an unauthorized user requires a fix.

**Comment by danielkryska** [comment]
> Tested on [581ba96](https://github.com/cyfronet-fid/sat4envi/commit/581ba967aaf33920d508f0da39c8c96ec00c35b3).
> 
> #### Authorization problem
> 1. Go to map, unauthorized (logout if needed).
> 2. You get redirected to login, and cannot access the map. (If you click "przejdź do mapy", then you are redirected back to login).
> 
> #### Search navigation
> 1. Focus the search bar. Wait for basic results.
> 2. Type quickly "war" and hit Enter. Nothing happens, this problem is fixed.
> 3. When you hit enter again upon results loading you get to Wargawa.
> 4. Hit down arrow. Results show up. Try to navigate the results with arrows, go down 1 position to Wara, click Enter. Nothing happens, I would expect to be able to select an alternative result though.
> 5. This behaviour is inconsistent though. When you type Wargowo and are presented with two results, then choosing either one using the same method (with arrows) works. Yet, when you type "Tychów " and also two results appear, then choosing doesn't work again.
> 
> There's some inconsistency in this behaviour. It doesn't seem like blocker to me though. Nevertheless, not being able to browse as an unauthorized user requires a fix.

Going to map as an unauthorized user have been fixed.

**Review by jswk — APPROVED** [review]
The unauthorized bug (see [Authorization problem in my previous comment](https://github.com/cyfronet-fid/sat4envi/pull/1056#pullrequestreview-561695799)) is now fixed. Apart from the non-blocking problems with search it's ok to merge.

**Comment by Marcelinna** [comment]
please delete "fix redirect to settings dashboard" from name od PR, this bug isnt fixed. 
And in the description write  "Add map scale in map left top corner". Scal is added to bottom left corner.

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
