### PR TITLE
[#1167] Update label in token generation modal

### PR DESCRIPTION
**Pull request by danielkryska**

### CODE REVIEW

**Comment by Marcelinna** [comment]
Plase change to "Twoje hasło do konta Sat4Envi"

**Comment by danielkryska** [comment]
@bwilk decided to rename it as it is. 

```
Desired wording
"Hasło konta Sat4Envi"
```

Please check #1167 the issue description

**Comment by danielkryska** [comment]
In case if you want to change the scope of the ticket, please write on the #sat4envi channel.

**Comment by Marcelinna** [comment]
I talked with @abacz that it will be better this way ""Twoje hasło do konta Sat4Envi""

**Comment by abacz** [comment]
I agree with @Marcelinna

**Comment by danielkryska** [comment]
done

**Review by Marcelinna — APPROVED** [review]

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
