### PR TITLE
[#566] resize `Warstwy` segment in `/map` sidebar, [Fix] Update UI messages

### LINKED ISSUE #566: [Fix] Minor fixes
- [x] Login as `zkAdmin`, open blitz  button and go to `Generuj raport`, field `Notatka` is marked as required, but passes on empty.
Test Run S4E #2
- [x] [Fix] Show errors in `Generuj raport` modal form
- [x] Add toggling ability to `Warstwy` element in sidebar on drag top edge (`/map` site)
- [x] [Fix] Search reset button should appear only when input non-empty on `/map`, `/settings` (sidebar), `settings/dashboard` (for admin@mail.pl)
- [x] Change `institution edition` form to invalid on image conversion error

Source: #515 
- [x] Change errors information's (np "Niepoprawny login / hasło") to be more visible
image

* [x] ~~[Fix] "+/-" buttons on map stay active after click (it shouldn't)~~
**It's build-in functionality and changing it will be more diffcult than outcome of fix**

Source: #552
- [x] text in "Tytuł" field should be in placeholder instead in value, on add new
image

Source: #547
- [x] use consistently capitalize letters in tab `Zarządzanie kryzysowe`
image
- [x] When sending a message with the current view (ZkAdmin Menu ->Wyślij widok jako wiadomość) in the "Dodatkowe informacje" field is a text, that should be changed.
image
- [x] In the ZkAdmin menu there, when opening the "Zapisz widok" menu, the modal that pops up has a different name "Zapisz konfigurację widoku". The same with other options on this menu. We should reconsider, how it should be. Here is a document for the suggested changes: https://docs.cyfronet.pl/pages/viewpage.action?pageId=74812728
image
image

### PR DESCRIPTION
**Pull request by danielkryska**
- [x] Login as `zkAdmin`, open blitz  button and go to `Generuj raport`, field `Notatka` is marked as required, but passes on empty.
Test Run S4E #2
- [x] [Fix] Show errors in `Generuj raport` modal form
- [x] Add vertical resize ability to `Warstwy` element in sidebar on drag top edge (`/map` site)
- [x] [Fix] Search reset button should appear only when input non-empty on `/map`, `/settings` (sidebar), `settings/dashboard` (for admin@mail.pl)
- [x] Change `institution edition` form to invalid on image conversion error

Source: #515 
- [x] Change errors information's (np "Niepoprawny login / hasło") to be more visible
image

* [x] ~~[Fix] "+/-" buttons on map stay active after click (it shouldn't)~~
**It's build-in functionality and changing it will be more diffcult than outcome of fix**

Source: #552
- [x] text in "Tytuł" field should be in placeholder instead in value, on add new
image

Source: #547
- [x] use consistently capitalize letters in tab `Zarządzanie kryzysowe`
image
- [x] When sending a message with the current view (ZkAdmin Menu ->Wyślij widok jako wiadomość) in the "Dodatkowe informacje" field is a text, that should be changed.
image
- [x] In the ZkAdmin menu there, when opening the "Zapisz widok" menu, the modal that pops up has a different name "Zapisz konfigurację widoku". The same with other options on this menu. We should reconsider, how it should be. Here is a document for the suggested changes: https://docs.cyfronet.pl/pages/viewpage.action?pageId=74812728
image
image

Closes #566

### CODE REVIEW

**Comment by danielkryska** [comment]
> I'd find something more fitting than "Minor fixes", also, fix actually rarely is fixed. The commit message also doesn't have a blank line after the first, so it's misformatted.
**fix actually rarely is fixed** What do you exactly mean by it? 
> 
> The resizing of the layers panel works strangely (FF78).
> out
**It's a case of styling it. Left for Andrzej Bacz to do it later. All CSS styling and shaping view is a separate work case, that's for the future reviews of yours.**
> 
> I also cannot toggle the layers panel.
**As we see on the gif, you're doing it...** 
> 
> Apart from these few issues, rest of the bullet points are addressed and work properly.
**Could you comment in more clear way of describing your expectations?** 

Why?
- It's more clear for me what should be done (I believe that I can fix some of found by you `things`, but not in a way you want them)
- Expectations (actions to be done) are a simple todo list, without summaries and opinions that are misleading or duplicate pieces of information of feedback (**The commit message also doesn't have a blank line after the first === so it's misformatted**)

Examples

1. **The resizing of the layers panel works strangely (FF78)**

How it can look as expectation (action to be done)
**Layers panel:**
- **Shouldn't resize on toggling**
- **Should resize more smoothly**

2. **I'd find something more fitting than "Minor fixes"**

How it can look as expectation (action to be done)
**Ticket should be updated by**
- **Title should mention that contain `Layers toggle`**
- **`Layers toggle` should be extracted from fixes in description**
- ...

3. **The commit message also doesn't have a blank line after the first, so it's misformatted.**

How it can look as expectation (action to be done)
**Add an empty line after ticket title in commit**

**Comment by danielkryska** [comment]
1. Blank line added to commit
2. Toggle doesn't contain animation of resizing. The case of not hiding fully is related to the CSS style of an element and will be continued by Andrzej Bacz.

**Comment by jswk** [comment]
> > I'd find something more fitting than "Minor fixes", also, fix actually rarely is fixed. The commit message also doesn't have a blank line after the first, so it's misformatted.
> 
> **fix actually rarely is fixed** What do you exactly mean by it?

Unless a previous fix was faulty, you don't fix it. The commit message read `[Fix] Minor fixes`, which suggested you fix fixes in it. On the other hand, you can actually fix a faulty mechanism, or a part of the system.

> > The resizing of the layers panel works strangely (FF78).
> 
> **It's a case of styling it. Left for Andrzej Bacz to do it later. All CSS styling and shaping view is a separate work case, that's for the future reviews of yours.**

I still think it would be better not to introduce bugs on such basic level, but ok.

> > I also cannot toggle the layers panel.
> 
> **As we see on the gif, you're doing it...**

No, I'm not. I'm **resizing** it. I'm not transitioning between two distinct states, as per [definition of toggle](https://www.thefreedictionary.com/toggle). You could say that it's toggling the horizontal size, but that's a bug, and not a desired behavior.

> **Could you comment in more clear way of describing your expectations?**
> 
> Why?
> 
>     * It's more clear for me what should be done (I believe that I can fix some of found by you `things`, but not always in a way you expected it)
> 
>     * Expectations (actions to be done) are a simple todo list, without summaries and opinions that are misleading or duplicate pieces of information of feedback (**The commit message also doesn't have a blank line after the first === so it's misformatted**)
> 
> 
> Examples
> 
>     1. **The resizing of the layers panel works strangely (FF78)**
> 
> 
> How it can look as expectation (action to be done)
> **Layers panel:**
> 
>     * **Shouldn't resize horizontally on toggling**
> 
>     * **Should resize verticaly more smoothly**
> 
> 
>     1. **I'd find something more fitting than "Minor fixes"**
> 
> 
> How it can look as expectation (action to be done)
> **Ticket should be updated by**
> 
>     * **Title should mention that contain `Layers toggle`**
> 
>     * **`Layers toggle` should be extracted from fixes in description**
> 
>     * ...
> 
> 
>     1. **The commit message also doesn't have a blank line after the first, so it's misformatted.**
> 
> 
> How it can look as expectation (action to be done)
> **Add an empty line after ticket title in commit**

I clearly missed the expectation part. I've assumed the way of being faulty is obvious, which isn't the case.

To restate, these are my suggestions:
 * Add empty line after the first line in commit message.
 * Change commit message heading to something more descriptive, e.g. `[#566] Update UI messages and improve behavior`.
 * Change toggle (in code, commit message) to resize, as I mentioned before.
 * Layers panel resizing
   * Don't skip vertically on release
   * Don't toggle horizontal size while resizing

**Comment by danielkryska** [comment]
Thank you very much for the answer for my questions and remarks. Your new comment is a whole better than the previous one and most importantly clear.

**Comment by danielkryska** [comment]
- [x] Add empty line after the first line in commit message.
- [x] Change commit message heading to something more descriptive, e.g. [#566] Update UI messages and improve behavior.
- [x] Change toggle (in code, commit message) to resize, as I mentioned before.
- [x] Layers panel resizing (these you say @abacz will fix later on)
- [x] Don't skip vertically on release
**on mouse release stay in place (Max height is 450px, min 0px, so there are limits of movement)**
- [ ] ~~Don't toggle horizontal size while resizing~~
**it won't toggle, only resize**

**Comment by danielkryska** [comment]
> [Fix] Search reset button should appear only when input non-empty on /map, /settings (sidebar), settings/dashboard (for admin@mail.pl) what about the reset button in settings/institutions - there is no search reset button
**It isn't scope of this ticket + this is different search**

> Add vertical resize ability to Warstwy element in sidebar on drag top edge (/map site) - it is difficult to drag Wartwy element with the button. The whole area of the button should be clickable, not only the thin line.
**I'll try to update resize option with center element, but I'm not sure if it will be available with actual used technology**

**Pull request merged**
