### PR TITLE
Change user profile view

### PR DESCRIPTION
**Pull request by danielkryska**
- Add section `remove user`

### CODE REVIEW

**Comment by kmarszalek** [comment]
in section 'Usuwanie konta' there is a button 'zmień hasło'? 

Zrzut ekranu 2020-11-26 o 09 12 58

**Review by jswk — CHANGES_REQUESTED** [review]
by @kmarszalek:
> in section 'Usuwanie konta' there is a button 'zmień hasło'?
> 
> Zrzut ekranu 2020-11-26 o 09 12 58

@danielkryska re-request review once the PR is ready

**Review by jswk — CHANGES_REQUESTED** [review]
1. The password input in removeUser should only be validated to be not empty, but not require minimum length.
2. When input password is invalid modal shouldn't show.
3. Currently when password is invalid, then I'm logged out, instead of just getting info that password is invalid.

**Review by michal-szostak — CHANGES_REQUESTED** [review]

**Review by jswk — APPROVED** [review]
All the points (1,2,3) from my previous review are solved, thanks!

I'd expect also to see a notification that removal was complete on being redirected to /login after successful operation, but it's non-blocking for me.

**Comment by jswk** [comment]
Since you're also modifying register page, I'd add a back-link to the main view there. Analogously as there is one in login view.

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
