### PR TITLE
Combined navigation and bugs

### PR DESCRIPTION
**Pull request by abacz**
- new navigation
- improved registration page
- login/register page sidebar height fixed
- switched position eye <-> star in sidebar
- RWD WMS layers fixed
- few minor visual bugs fixed
- minor style bugs
- add tabs WMS in settings
- improved legend
- improved timeline live button

### CODE REVIEW

**Review by danielkryska — APPROVED** [review]

**Comment by Marcelinna** [comment]
image
image

When I am on the List of Product, Favorites are lighter. I think it isnt intutitive

**Comment by Marcelinna** [comment]
After each click on a product at the end of the page (eg. Sentinel), a reload takes place and we return to the top of the product list

**Comment by Marcelinna** [comment]
logos on the login page could transfer to the appropriate institutions

**Comment by abacz** [comment]
> logos on the login page could transfer to the appropriate institutions
For further consideration

**Comment by Marcelinna** [comment]
Problem with button 
image

**Comment by Marcelinna** [comment]
Lack of  " <= Przejdź do mapy" on register page

**Comment by abacz** [comment]
> Problem with button
> image

Fixed

**Comment by abacz** [comment]
> logos on the login page could transfer to the appropriate institutions and they hide in lower screen resolution, on register page don't visible below 800px
> image
> image

Fixed

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
