### PR TITLE
[#898] choose dashboard by number of institutions

### LINKED ISSUE #898: Choose dashboard by number of institutions
- user with a 1 administration institution
  - should have activated the institution from beginning
  - should have disabled search
  - preview: https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414649284

- user with more than the 1 institution
  - should have different dashboard
  - preview: https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414671409

### PR DESCRIPTION
**Pull request by danielkryska**
IMPORTANT!!! Tile `Dedykowane warstwy` from first image aren't in scope of this PR.

Fixes
- Fix choose institution
- Fix breadcrumbs navigation
- Add email validator to invitation form 
- Display and hide sidbar on map, on burger click
- Hide mobile nav-bar on navigate 

--- 

image

- user with a 1 administration institution
  - should it have activated
  - should have disabled search
  - preview: https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414649284

---

image

- user with more than a 1 institution
  - should have different dashboard
  - [fix] images
  - [fix] institutions search in tile
  - preview: https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414671409

Closes #898

### CODE REVIEW

**Comment by Marcelinna** [comment]
When the user is on page /settings/dashboard and from the section search chose e.g Zarządzanie kryzysowe - Mazowieckie and nex click the button <_Zarządzaj>, user should be redirected on Profil instytucji, not on Lista instytucji.

**Review by abacz — COMMENTED** [review]
- after first login when i go to settings, Profile appear. Second time is Dashboard.
- manage button in "zarządzaj instytucjami" box is disabled until you choose institution to manage. It should be always active.

**Review by jswk — CHANGES_REQUESTED** [review]
Apart from the things identified by @abacz, there are several issues (noticed on deployment of 81025e0).
3. When I log in as zkWawAdmin@mail.pl I cannot manage members. I.e. when I click on the "Ludzie" button in the sidebar or "Zarządzaj ludźmi" in the dashboard I get redirected back to the dashboard. Expected behaviour is to be able to manage members and not be momentarily redirected.
4. The institution name is not dynamic for a single institution admin (for example zkWawAdmin@mail.pl).
image

**Comment by Marcelinna** [comment]
When the user clicks on the button <_Osoby w tej instytucji> he is redirected to the  /settings/dashboard

**Review by michal-szostak — APPROVED** [review]
If @Marcelinna / @abacz say it's good then alright. Codewise I have no complains.

**Review by jswk — CHANGES_REQUESTED** [review]
> 3. When I log in as [zkWawAdmin@mail.pl](mailto:zkWawAdmin@mail.pl) I cannot manage members. I.e. when I click on the "Ludzie" button in the sidebar or "Zarządzaj ludźmi" in the dashboard I get redirected back to the dashboard. Expected behaviour is to be able to manage members and not be momentarily redirected.
> 4. The institution name is not dynamic for a single institution admin (for example [zkWawAdmin@mail.pl](mailto:zkWawAdmin@mail.pl)).
> image

The problems 3 and 4 I commented on before are still not fixed.

5. Apart from that, in the new layout, I would expect the institution context to reset once you click to select an institution. This doesn't happen though and the view is inconsistent:
image

**Comment by Marcelinna** [comment]
When user click in search box in dashboard, see empty Institution Profile
image

**Review by jswk — CHANGES_REQUESTED** [review]
(All this is about aaefd37c deployment.)

My points up to date had been addressed, thanks!

I've noticed yet another place with static "Urząd Miasta Kraków", in people management view:
image
I also have the same problem as @Marcelinna, i.e. clicking on the search navigates to an empty profile. Moreover, it's impossible to navigate away from the "Change password" view (the buttons don't work).
image


Other than that the functionality now seems more solid.

**Review by jswk — CHANGES_REQUESTED** [review]
(by @Marcelinna)
> When user click in search box in dashboard, see empty Institution Profile
> image

The quoted issue is still valid though.

**Comment by danielkryska** [comment]
> (by @Marcelinna)
> 
> > When user click in search box in dashboard, see empty Institution Profile
> > image
> 
> The quoted issue is still valid though in [dfe3c8e](https://github.com/cyfronet-fid/sat4envi/commit/dfe3c8eef25d021d2532fe2718b869aec2c897d2) deployment.

It's other sort of bug and will be repaired in other PR

**Review by jswk — APPROVED** [review]

**Pull request merged**
