### PR TITLE
[#1200] Update map loader with custom one

### PR DESCRIPTION
**Pull request by abacz**

### CODE REVIEW

**Comment by jswk** [comment]
image

The current way the new loader looks doesn't match the prev: https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/425983640_Mapa_-__scena_-_Timeline_-_Wybieranie_Godziny. I understand this is still WIP @danielkryska?

**Review by danielkryska — APPROVED** [review]

**Comment by Marcelinna** [comment]
I think loader shouldnt be visible on error page @abacz ?
image

**Comment by Marcelinna** [comment]
> image
> 
> The current way the new loader looks doesn't match the prev: https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/425983640_Mapa_-__scena_-_Timeline_-_Wybieranie_Godziny. I understand this is still WIP @danielkryska?

loader still doesnt match the prev.

**Review by Marcelinna — APPROVED** [review]

**Comment by danielkryska** [comment]
The loader seems to work correctly now.

loader

**Pull request merged**
