### PR TITLE
[Fix] Footprint, regular member visible elements, login error, validae image WMS

### PR DESCRIPTION
**Pull request by danielkryska**
- [Fix] remove a footprint from search params on a polygon removal from the map
- Remove a invitation edition
- [Fix] Hide sub navigation in an institution profile if a user is just a member
- [Fix] Image WMS validation while add a new overlay
  - Fetch capabilitites and set URL LAYERS AND STYLES if are undefined
  - BBOX URL param now can have a negative values
  - Server reponse should validate response content-type and should be image/*
  - Pass all params added by user in URL
  - Change resolution of validated images

Examples of passing urls:
https://wody.isok.gov.pl/gpservices/KZGW/MZP20_Predkosc_WysokiePrawdopodPowodzi/MapServer/WMSServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=1,2,3,4,5,6,7,8,9,10&CRS=EPSG:4326&STYLES=&WIDTH=1940&HEIGHT=1020&BBOX=-49.497526,14.407200,54.573956,-23.836237
https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer
https://wody.isok.gov.pl/gpservices/KZGW/MZP20_Predkosc_WysokiePrawdopodPowodzi/MapServer/WMSServer
https://eumetview.eumetsat.int/geoserver/wms?service=wms&version=1.3.0&request=GetCapabilities
https://mapy.geoportal.gov.pl/wss/service/INSPIRE_TN_TBD/guest
https://mapy.geoportal.gov.pl/wss/service/INSPIRE_TN_BDO/guest

Examples of XML Error responses URLS:
https://wody.isok.gov.pl/gpservices/KZGW/MZP20_Predkosc_WysokiePrawdopodPowodzi/MapServer/WMSServer?LAYERS=
https://wody.isok.gov.pl/gpservices/KZGW/MZP20_Predkosc_WysokiePrawdopodPowodzi/MapServer/WMSServer?STYLES=

### CODE REVIEW

**Review by michal-szostak — APPROVED** [review]

**Comment by Marcelinna** [comment]
Hide sub navigation in an institution profile is also for administrator profile

**Comment by Marcelinna** [comment]
[Fix] inconsistent login behaviour #841-> I cant check this properly because now after made mistake use is redirected to /map

**Review by jswk — CHANGES_REQUESTED** [review]
#841 isn't fixed. When I make a mistake and then correct myself then I stay at login page with cleared input.

When adding a WMS overlay from a capabilities document, I don't get to choose a particular layer. For example, for https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer all the layers are added, there is no ability to choose a particular one. This behaviour should at least be described when adding an overlay.

**Comment by danielkryska** [comment]
> #841 isn't fixed. When I make a mistake and then correct myself then I stay at login page with cleared input.

If it isn't, let's it be so. This thread will be continued in other PR.
 
> When adding a WMS overlay from a capabilities document, I don't get to choose a particular layer. For example, for https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer all the layers are added, there is no ability to choose a particular one. This behaviour should at least be described when adding an overlay.

I have updated description while adding new overlay.

**Review by jswk — APPROVED** [review]

**Pull request merged**
