### PR TITLE
Fixes for: drawing polygon, institution form, admin dashboard

### PR DESCRIPTION
**Pull request by danielkryska**
- Skip s3 image loading error (empty response or 404 response) in institution form
- [Fix] Disable parent selection in institution edit mode and add institution child mode
- Remove `add_child` query param from URL on add child institution
- [Fix] Disable polygon drawing when products tab is on (should work only in sentinel search mode)
- [Fix] Multiple institutions admin is redirected to institutions list when go to /settings URL
- Remove breadcrumbs functionality from code
- [Fix] Inconsistent navigation in settings (landing on different pages)

### CODE REVIEW

**Comment by kmarszalek** [comment]
if you load product and then go to search you can draw polygon on loaded product. but if you are on product list you cant.so i would leave it as a bug?
Zrzut ekranu 2020-12-1 o 15 15 51

**Comment by kmarszalek** [comment]
why dont you unable the field with parent in while editing institution, now i can choose diff parent and save but my parent wont change..

**Review by kmarszalek — CHANGES_REQUESTED** [review]
as described in previous comments

**Review by kmarszalek — APPROVED** [review]
should work 👍

**Review by Marcelinna — APPROVED** [review]

**Review by kmarszalek — CHANGES_REQUESTED** [review]
found one, you can still edit parent institution. even if it doesnt change anything on save.

**Review by michal-szostak — APPROVED** [review]

**Comment by danielkryska** [comment]
> found one, you can still edit parent institution. even if it doesn't change anything on save.

I don't know which browser do you use or what state of store do you have, but the input is disabled on edition and adding child. Unfortunately there is an other bug that can cause opening modal. Label click call function that allow change of the institution parent.

This issue will be fixed in other PR.

**Review by kmarszalek — APPROVED** [review]

**Pull request merged**
